# Generated by Django 6.1.1 on 2026-09-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_item_requirements', to='restaurant.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='restaurant.menuitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'inventory_item'), name='unique_menu_item_inventory_requirement'), models.CheckConstraint(condition=models.Q(('quantity_required__gt', 0)), name='positive_quantity_required')],
            },
        ),
    ]
